# -*- mode: python ; coding: utf-8 -*-
# 单文件打包配置 - 更适合分发

import sys
import os

block_cipher = None

a = Analysis(
    ['gui_app.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('harmony_modules_config.json', '.'),
        ('.env.example', '.'),
    ],
    hiddenimports=[
        'tkinter',
        'tkinter.ttk',
        'tkinter.filedialog',
        'tkinter.messagebox',
        'tkinter.scrolledtext',
        'asyncio',
        'threading',
        'pathlib',
        'datetime',
        'dotenv',
        'python-dotenv',
        'google',
        'google.genai',
        'google.genai.types',
        'crawl4ai',
        'crawl4ai.async_configs',
        'crawl4ai.async_crawler_strategy',
        'crawl4ai.async_webcrawler',
        'playwright',
        'playwright.sync_api',
        'playwright.async_api',
        'beautifulsoup4',
        'bs4',
        'lxml',
        'lxml.html',
        'aiofiles',
        'aiohttp',
        'certifi',
        'charset_normalizer',
        'idna',
        'urllib3',
        'requests',
        'main',
        'config',
        'config.manager',
        'ai',
        'ai.content_processor',
        'ai.prompts',
        'crawler',
        'crawler.core',
        'crawler.file_saver',
        'crawler.spa_handler',
        'batch',
        'batch.processor',
        'arkts_lint',
        'arkts_lint.rules_extractor',
        'utils',
        'utils.helpers',
        'gemini_api',
        'module_manager',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyd_a = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyd_a,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='HarmonyOS规则爬虫工具',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,  # 不显示控制台窗口
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='icon.ico' if os.path.exists('icon.ico') else None,
)
